# Generated by Django 6.0.6 on 2026-07-30 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_banner_profile_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile',
            new_name='ProfileImage',
        ),
    ]
