# Generated by Django 6.0.6 on 2026-07-30 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_profile_profile_profileimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='ProfileImage',
            new_name='profile_image',
        ),
    ]
