# Generated by Django 6.0.6 on 2026-08-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_profileimage_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='onboarded',
            field=models.BooleanField(default=False),
        ),
    ]
