# Generated by Django 6.0.6 on 2026-08-05 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_profile_onboarded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='onboarded',
        ),
    ]
