# Generated by Django 6.0.6 on 2026-08-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_profile_onboarded'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='onboarded',
            field=models.BooleanField(default=False),
        ),
    ]
